#\!/bin/bash

echo "🔧 Setting up Vercel Environment Variables for Supabase"
echo "=================================================="
echo ""
echo "Please run the following commands in your terminal:"
echo ""
echo "1. Login to Vercel:"
echo "   npx vercel login"
echo ""
echo "2. Set up the environment variables:"
echo "   npx vercel env add REACT_APP_DATABASE_PROVIDER"
echo "   # Enter: supabase"
echo ""
echo "   npx vercel env add REACT_APP_DATABASE_AUTO_SWITCH"
echo "   # Enter: true"
echo ""
echo "   npx vercel env add REACT_APP_DATABASE_FALLBACK"
echo "   # Enter: true"
echo ""
echo "   npx vercel env add REACT_APP_SUPABASE_URL"
echo "   # Enter: https://kmxipuaqierjqaikuimi.supabase.co"
echo ""
echo "   npx vercel env add REACT_APP_SUPABASE_ANON_KEY"
echo "   # Enter: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteGlwdWFxaWVyanFhaWt1aW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjU2NDUsImV4cCI6MjA2NjAwMTY0NX0.2S3cAnBh4zDFFQNpJ-VN17YrSJXyclyFjywN2izuPaU"
echo ""
echo "3. Redeploy your application:"
echo "   npx vercel --prod"
echo ""
echo "=================================================="
echo "Note: Make sure to select 'Production' environment when adding the variables\!"
EOF < /dev/null